### ISSUE TITLE
Duplicate function in callback file

### ISSUE THREAD

**Issue by barkermrl** [trustwiseai/trustwise#3]
The `validate_api_key` function appears in `callback.py` and `request.py`. Can we either delete one or move them to a separate file?

https://github.com/trustwiseai/trustwise/blob/ddcb045664384e382e19b9bd39fbc751d78d2622/trustwise/callback.py#L30C1-L46C20

https://github.com/trustwiseai/trustwise/blob/ddcb045664384e382e19b9bd39fbc751d78d2622/trustwise/request.py#L26C1-L43C1

**Comment by nbhatnagar-tw** [comment]
Removed the duplicate function and moved it to utils.py
