### ISSUE TITLE
Code similar to LlamaDebugHandler

### ISSUE THREAD

**Issue by barkermrl** [trustwiseai/trustwise#4]
The code for our CallbackHandler is here:
https://github.com/trustwiseai/trustwise/blob/ddcb045664384e382e19b9bd39fbc751d78d2622/trustwise/callback.py#L49

It is very similar to the LlamaIndexDebugHandler:
https://github.com/run-llama/llama_index/blob/main/llama_index/callbacks/llama_debug.py#L15

Is this by design, and should we inherit instead?

**Comment by mbarker-tw** [comment]
After discussion, this is by design to avoid external dependency.
